export const TOGGLE_MODAL_FORM_DETAIL = "TOGGLE_MODAL_FORM_DETAIL";
export const TOGGLE_MODAL_IMAGE = "TOGGLE_MODAL_IMAGE";
export const ADD_MODAL_IMAGE_URL = "ADD_MODAL_IMAGE_URL";
export const ADD_TRANSACTIONS = "ADD_TRANSACTIONS";
export const ADD_TRANSACTION = "ADD_TRANSACTION";
export const LOADING_TOGGLE = "LOADING_TOGGLE";
